import Foundation

enum RotationDirection: String, CaseIterable, Codable, Identifiable, Sendable {
    case counterclockwise
    case clockwise

    var id: String { rawValue }

    var title: String {
        switch self {
        case .counterclockwise: "逆时针"
        case .clockwise: "顺时针"
        }
    }

    var symbol: String {
        switch self {
        case .counterclockwise: "arrow.counterclockwise"
        case .clockwise: "arrow.clockwise"
        }
    }
}

struct MetronomePreset: Codable, Hashable, Sendable {
    var bpm: Int
    var beats: Int
    var subdivision: Int
    var direction: RotationDirection
    var grouping: String

    static let standard = MetronomePreset(
        bpm: 112,
        beats: 4,
        subdivision: 1,
        direction: .counterclockwise,
        grouping: "标准"
    )

    static let builtIns: [(name: String, bpm: Int)] = [
        ("慢", 72),
        ("中速", 112),
        ("快", 144)
    ]

    /// 0 is the migration-safe sentinel for half-note training. The remaining
    /// values are the number of pulses inside one main beat.
    static let supportedSubdivisions = [0, 1, 2, 4]

    static func groupings(for beats: Int) -> [String] {
        switch beats {
        case 5: ["2+3", "3+2"]
        case 7: ["3+4", "4+3"]
        default: ["标准"]
        }
    }

    var normalized: MetronomePreset {
        var result = self
        result.bpm = min(max(result.bpm, 30), 240)
        result.beats = min(max(result.beats, 3), 9)
        if !Self.supportedSubdivisions.contains(result.subdivision) {
            result.subdivision = 1
        }
        let validGroupings = Self.groupings(for: result.beats)
        if !validGroupings.contains(result.grouping) {
            result.grouping = validGroupings[0]
        }
        return result
    }

    var tempoName: String {
        switch bpm {
        case ..<55: "Largo"
        case ..<76: "Adagio"
        case ..<108: "Andante"
        case ..<120: "Moderato"
        case ..<168: "Allegro"
        case ..<200: "Presto"
        default: "Prestissimo"
        }
    }

    var tempoDisplay: String {
        "\(tempoName) · \(bpm) BPM"
    }

    var subdivisionTitle: String {
        switch subdivision {
        case 0: "二分音符"
        case 2: "八分音符"
        case 4: "十六分音符"
        default: "四分音符"
        }
    }

    var subdivisionShortTitle: String {
        switch subdivision {
        case 0: "2 分"
        case 2: "8 分"
        case 4: "16 分"
        default: "4 分"
        }
    }

    /// Pulses scheduled inside each geometric beat. Half notes remain one
    /// pulse per beat, while their interval is stretched by `eventDensity`.
    var pulsesPerBeat: Int {
        max(1, subdivision)
    }

    /// Relative rhythmic density with a quarter note as 1.0.
    var eventDensity: Double {
        subdivision == 0 ? 0.5 : Double(subdivision)
    }

    var mainBeatDuration: TimeInterval {
        60 / Double(bpm) / min(1, eventDensity)
    }

    var compactSummary: String {
        "\(bpm) BPM · \(beats) 拍 · \(subdivisionTitle)"
    }

    var groupStartIndices: Set<Int> {
        if grouping == "标准" {
            return beats == 4 ? [0, 2] : [0]
        }
        let groupSizes = grouping.split(separator: "+").compactMap { Int($0) }
        var starts: Set<Int> = [0]
        var runningTotal = 0
        for size in groupSizes.dropLast() {
            runningTotal += size
            starts.insert(runningTotal)
        }
        return starts
    }

    /// Primary accents. The 7-beat 4+3 pattern follows the V4 music-design
    /// table: beat 5 begins the second group with another strong accent.
    var strongBeatIndices: Set<Int> {
        if beats == 7, grouping == "4+3" {
            return [0, 4]
        }
        return [0]
    }

    /// Secondary accents generated by the rhythmic structure. The unusual
    /// beat 3 accent in 7-beat 4+3 is deliberate and documented in V4.
    var secondaryAccentIndices: Set<Int> {
        if beats == 7, grouping == "4+3" {
            return [2]
        }
        return groupStartIndices.subtracting(strongBeatIndices)
    }
}
